import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
test('Appairage, challenge à usage unique, fichiers privés et révocation', async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'maison-api-'));
  const port = 19000 + crypto.randomInt(10000);
  const processServer = spawn(process.execPath, ['server/index.mjs'], { env: { ...process.env, PORT: String(port), MAISON_DATA: root } });
  let log = '';
  const code = await new Promise((resolve, reject) => { const timer = setTimeout(() => reject(Error('Démarrage trop long')), 10000); processServer.on('error', reject); processServer.stdout.on('data', data => { log += data; const match = /minutes\) : (\d{6})/.exec(log); if (match) { clearTimeout(timer); resolve(match[1]); } }); });
  const request = async (route, method = 'GET', body, token) => { const response = await fetch(`http://127.0.0.1:${port}/api/v1/${route}`, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: body ? JSON.stringify(body) : undefined }); return { status: response.status, body: await response.json() }; };
  try {
    assert.equal((await request('files')).status, 401);
    assert.equal((await request('cameras/discover', 'POST', {})).status, 401);
    assert.equal((await request('cameras/unknown/snapshot')).status, 401);
    const keys = crypto.generateKeyPairSync('ec', { namedCurve: 'prime256v1' });
    const publicKey = keys.publicKey.export({ type: 'spki', format: 'pem' });
    assert.equal((await request('pair', 'POST', { code: 'bad', publicKey })).status, 403);
    const paired = await request('pair', 'POST', { code, publicKey, name: 'Test' }); assert.equal(paired.status, 201);
    const deviceId = paired.body.deviceId;
    const challenge = await request('auth/challenge', 'POST', { deviceId });
    const signature = crypto.sign('sha256', Buffer.from(challenge.body.challenge), keys.privateKey).toString('base64');
    const session = await request('auth/session', 'POST', { deviceId, signature }); assert.equal(session.status, 200);
    assert.equal((await request('auth/session', 'POST', { deviceId, signature })).status, 403);
    const token = session.body.token;
    assert.equal((await request('settings','GET',undefined,token)).status,200);
    const room=await request('rooms','POST',{name:'Salon'},token);assert.equal(room.status,200);
    assert.equal((await request('rooms','GET',undefined,token)).body[0].name,'Salon');
    const backup=await request('backup','GET',undefined,token);assert.equal(backup.body.secretsIncluded,false);assert.ok(!JSON.stringify(backup.body).includes(token));
    assert.equal((await request('home/devices','POST',{address:'127.0.0.1',component:'switch:0'},token)).status,400);
    const newKeys=crypto.generateKeyPairSync('ec',{namedCurve:'prime256v1'});const secondary=await request('pair','POST',{code,publicKey:newKeys.publicKey.export({type:'spki',format:'pem'}),name:'Invité'});
    const secondaryChallenge=await request('auth/challenge','POST',{deviceId:secondary.body.deviceId});const secondarySignature=crypto.sign('sha256',Buffer.from(secondaryChallenge.body.challenge),newKeys.privateKey).toString('base64');const secondarySession=await request('auth/session','POST',{deviceId:secondary.body.deviceId,signature:secondarySignature});
    assert.equal((await request('backup','GET',undefined,secondarySession.body.token)).status,403);
    assert.equal((await request('settings','POST',{name:'Intrusion'},secondarySession.body.token)).status,403);
    assert.equal((await request('cameras/unknown/snapshot', 'GET', undefined, token)).status, 404);
    assert.equal((await request('cameras', 'POST', { sourceId: 'invented', source: '/etc/passwd' }, token)).status, 404);
    assert.equal((await request('server', 'GET', undefined, token)).status, 200);
    await fs.writeFile(path.join(root, 'media', 'film.mp4'), '0123456789');
    assert.equal((await request('files', 'GET', undefined, token)).body[0].name, 'film.mp4');
    const range = await fetch(`http://127.0.0.1:${port}/api/v1/files/content?path=film.mp4`, { headers: { Authorization: `Bearer ${token}`, Range: 'bytes=2-5' } }); assert.equal(range.status, 206); assert.equal(await range.text(), '2345');
    assert.equal((await request('files?path=..', 'GET', undefined, token)).status, 400);
    assert.equal((await request('devices/authorized/'+deviceId, 'DELETE', undefined, token)).status, 200);
    assert.equal((await request('server', 'GET', undefined, token)).status, 401);
    const saved = await fs.readFile(path.join(root, 'configuration.json'), 'utf8'); assert.ok(!saved.includes(token));
  } finally { processServer.kill(); await new Promise(resolve => processServer.on('exit', resolve)); await fs.rm(root, { recursive: true, force: true }); }
});
