const $ = s => document.querySelector(s);
const pages = [['home','⌂','Accueil'],['devices','◈','Appareils'],['cameras','▣','Caméras'],['media','▷','Médias'],['files','▤','Fichiers'],['server','▥','Serveur'],['more','⋯','Plus']];
let token = sessionStorage.getItem('token'); let current = 'home'; let stopCamera = () => {};
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const size = n => n > 1e9 ? (n/1e9).toFixed(1)+' Go' : (n/1e6).toFixed(0)+' Mo';
async function api(route) { const r = await fetch('/api/v1/'+route, {headers:{Authorization:'Bearer '+token}}); const v = await r.json(); if(!r.ok) throw Error(v.message); return v; }
$('#nav').innerHTML = pages.map(([id,icon,label])=>`<button data-page="${id}">${icon}　${label}</button>`).join('');
$('#nav').onclick = e => { const b=e.target.closest('button'); if(b) render(b.dataset.page); };
function empty(icon,title,description){return `<div class="card empty"><div class="icon">${icon}</div><h2>${title}</h2><p>${description}</p></div>`;}
async function pair(){ $('#content').innerHTML=`<div class="card pair"><div class="icon">⌁</div><h2>Connecter votre maison</h2><p>Autorisez ce navigateur avec le code affiché au démarrage du serveur. Une clé cryptographique est créée sur cet appareil.</p><form id="pair"><label>Code à six chiffres</label><input name="code" inputmode="numeric" pattern="[0-9]{6}" required placeholder="000000" maxlength="6"><button class="primary">Appairer cet appareil</button><p id="error" class="error"></p></form></div>`;
 $('#pair').onsubmit=async e=>{e.preventDefault(); try {const keys=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);const spki=await crypto.subtle.exportKey('spki',keys.publicKey);const b64=btoa(String.fromCharCode(...new Uint8Array(spki)));const pub=`-----BEGIN PUBLIC KEY-----\n${b64}\n-----END PUBLIC KEY-----`;const r=await fetch('/api/v1/pair',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:new FormData(e.target).get('code'),publicKey:pub,name:'Navigateur local'})});const p=await r.json();if(!r.ok)throw Error(p.message);const c=await fetch('/api/v1/auth/challenge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceId:p.deviceId})}).then(r=>r.json());const raw=new Uint8Array(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},keys.privateKey,new TextEncoder().encode(c.challenge)));const integer=bytes=>{let a=Array.from(bytes);while(a.length>1&&a[0]===0)a.shift();if(a[0]&128)a.unshift(0);return [2,a.length,...a];};const a=integer(raw.slice(0,32)),b=integer(raw.slice(32));const der=new Uint8Array([48,a.length+b.length,...a,...b]);const s=await fetch('/api/v1/auth/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceId:p.deviceId,signature:btoa(String.fromCharCode(...der))})});const result=await s.json();if(!s.ok)throw Error(result.message);token=result.token;sessionStorage.setItem('token',token);render('home');}catch(err){$('#error').textContent=err.message;}};
}
async function render(page){stopCamera();current=page;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#title').textContent=pages.find(p=>p[0]===page)?.[2]||'Ma Maison';if(!token)return pair();try{const stats=await api('server');$('#connection').textContent='● Connexion locale';$('#subtitle').textContent=stats.name+' · Votre serveur personnel';if(page==='home'||page==='server'){$('#content').innerHTML=`<div class="card hero"><span class="good">● Serveur en ligne</span><h2>${escape(stats.name)}</h2><p>Vos fichiers sont disponibles sur ce réseau.<br>L’accès distant sera proposé lorsqu’un transport sécurisé sera installé.</p></div><div class="grid"><div class="card"><div class="icon">▥</div><span class="metric">${size(stats.memory.total-stats.memory.free)}</span><span class="label">Mémoire utilisée sur ${size(stats.memory.total)}</span><progress max="${stats.memory.total}" value="${stats.memory.total-stats.memory.free}"></progress></div><div class="card"><div class="icon">▤</div><span class="metric">${size(stats.storage.free)}</span><span class="label">Espace disponible</span></div><div class="card"><div class="icon">◷</div><span class="metric">${Math.floor(stats.uptime/3600)} h</span><span class="label">Depuis le dernier démarrage</span></div></div><h3>Votre quotidien</h3><div class="grid"><button class="card secondary" data-go="files">▤　Parcourir mes fichiers</button><button class="card secondary" data-go="media">▷　Mes films et vidéos</button><button class="card secondary" data-go="more">⚙　Appareils autorisés</button></div>`;document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>render(b.dataset.go));}
else if(page==='cameras') await cameras();
else if(page==='files'||page==='media')await files('',page==='media');
else if(page==='more'){const devices=await api('devices/authorized');$('#content').innerHTML=`<div class="card"><h2>Appareils autorisés</h2>${devices.map(d=>`<div class="row"><span>${escape(d.name)}<small class="label">${d.revoked?'Accès révoqué':'Appareil appairé'}</small></span>${d.revoked?'':`<button class="secondary" data-revoke="${d.id}">Révoquer</button>`}</div>`).join('')}</div>`;document.querySelectorAll('[data-revoke]').forEach(b=>b.onclick=async()=>{if(!confirm('Révoquer l’accès de cet appareil ?'))return;await fetch('/api/v1/devices/authorized/'+b.dataset.revoke,{method:'DELETE',headers:{Authorization:'Bearer '+token}});render('more');});}
else $('#content').innerHTML=empty(page==='cameras'?'▣':'◈',page==='cameras'?'Aucune caméra configurée':'Votre maison prend forme','Ce module n’est pas encore installé. Sa disponibilité sera annoncée par le serveur.');
}catch(e){$('#content').innerHTML=empty('⌁','Connexion interrompue',escape(e.message));}}
async function files(folder, videos){const list=await api('files?path='+encodeURIComponent(folder));const filtered=list.filter(f=>!videos||f.directory||/\.(mkv|mp4|webm|avi)$/i.test(f.name));$('#content').innerHTML=`<div class="card"><h2>${videos?'Bibliothèque vidéo':'Fichiers partagés'}</h2><p>${escape(folder||'Votre espace personnel')}</p>${folder?'<button class="secondary" id="back">← Dossier parent</button>':''}${filtered.map((f,i)=>`<div class="row"><span>${f.directory?'▤':'▷'}　${escape(f.name)}<small class="label">${f.directory?'Dossier':size(f.size)}</small></span><button class="secondary" data-file="${i}">${f.directory?'Ouvrir':'Télécharger'}</button></div>`).join('')||'<p>Aucun fichier pour le moment. Ajoutez vos contenus dans le dossier partagé du serveur.</p>'}</div>`;if($('#back'))$('#back').onclick=()=>files(folder.split('/').slice(0,-1).join('/'),videos);document.querySelectorAll('[data-file]').forEach(b=>b.onclick=async()=>{const f=filtered[Number(b.dataset.file)];if(f.directory)return files(f.path,videos);const r=await fetch('/api/v1/files/content?path='+encodeURIComponent(f.path),{headers:{Authorization:'Bearer '+token}});if(!r.ok)return;const u=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=u;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),60000);});}
render(current);
async function post(route, value = {}) { const r = await fetch('/api/v1/'+route, {method:'POST', headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(value)}); const result = await r.json(); if(!r.ok)throw Error(result.message); return result; }
async function cameras(){
 const list=await api('cameras');
 $('#content').innerHTML=`<div class="card"><h2>Vos caméras</h2><p>Branchez une webcam USB à votre serveur, puis recherchez-la.</p><button class="primary" id="search-camera">+ Rechercher des caméras</button><p id="camera-message"></p><div id="camera-found"></div>${list.map((c,i)=>`<div class="row"><span>▣　${escape(c.name)}<small class="label">${c.online?'Connectée':'Débranchée ou inaccessible'}</small></span><button class="secondary" data-camera="${i}">Voir le direct</button></div>`).join('')||'<p>Aucune caméra ajoutée pour le moment.</p>'}</div><div id="camera-live"></div>`;
 $('#search-camera').onclick=async()=>{const button=$('#search-camera');button.disabled=true;try{const result=await post('cameras/discover');if(current!=='cameras')return;$('#camera-message').textContent=[result.message,...(result.warnings||[])].join(' ');const found=result.cameras.filter(c=>!list.some(item=>item.sourceId===c.sourceId));$('#camera-found').innerHTML=found.map((c,i)=>`<label class="row"><input class="camera-check" type="checkbox" value="${i}"><span>${escape(c.name)}</span></label>`).join('')+(found.length?'<button class="primary" id="add-cameras">Ajouter la sélection</button>':'');if($('#add-cameras'))$('#add-cameras').onclick=async()=>{const add=$('#add-cameras');add.disabled=true;try{for(const input of document.querySelectorAll('.camera-check:checked'))await post('cameras',{sourceId:found[Number(input.value)].sourceId});await cameras();}catch(e){$('#camera-message').textContent=e.message;add.disabled=false;}};}catch(e){if($('#camera-message'))$('#camera-message').textContent=e.message;}finally{button.disabled=false;}};
 document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>liveCamera(list[Number(b.dataset.camera)]));
}
function liveCamera(camera){stopCamera();const controller=new AbortController();let timer;let objectUrl;stopCamera=()=>{controller.abort();clearTimeout(timer);if(objectUrl)URL.revokeObjectURL(objectUrl);};$('#camera-live').innerHTML=`<div class="card"><h2>${escape(camera.name)}</h2><img id="live-image" alt="Direct webcam"><p id="live-status">Connexion au direct…</p><button class="secondary" id="camera-fullscreen">Plein écran</button></div>`;$('#camera-fullscreen').onclick=()=>$('#live-image').requestFullscreen();async function refresh(){if(controller.signal.aborted)return;try{const response=await fetch('/api/v1/cameras/'+camera.id+'/snapshot',{headers:{Authorization:'Bearer '+token},signal:controller.signal});if(!response.ok)throw Error((await response.json()).message);const blob=await response.blob();if(controller.signal.aborted)return;const previous=objectUrl;objectUrl=URL.createObjectURL(blob);$('#live-image').src=objectUrl;if(previous)URL.revokeObjectURL(previous);$('#live-status').textContent='Direct USB · Sans son';}catch(e){if(controller.signal.aborted)return;$('#live-status').textContent=e.message;}timer=setTimeout(refresh,300);}refresh();}
